name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: pwd; cd .. ; pwd ; ls ; cd .. ; pwd ; ls
      #- run: curl https://github.com/CodeIntelligenceTesting/jazzer/releases/download/v0.13.1/jazzer-linux.tar.gz
      #- run: tar xzvf jazzer-linux.tar.gz
      - run: ls -a
      
