name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls ${{ github.workspace }}
      - run: pwd; cd ../../../..; pwd; ls
      - run: pwd; ls; curl -v https://github.com/CodeIntelligenceTesting/jazzer/releases/download/v0.13.1/jazzer-linux.tar.gz; ls
      #- run: tar xzvf jazzer-linux.tar.gz
      - run: ls -a
      
